const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("codexDeck", {
  bootstrap: () => ipcRenderer.invoke("app:bootstrap"),
  newWindow: (payload) => ipcRenderer.invoke("window:new", payload),
  chooseWorkspace: (current) => ipcRenderer.invoke("dialog:workspace", current),
  chooseRecordHome: (current) => ipcRenderer.invoke("dialog:record-home", current),
  chooseImages: () => ipcRenderer.invoke("dialog:images"),
  notify: (payload) => ipcRenderer.invoke("app:notify", payload),
  officialLogin: (providerId) => ipcRenderer.invoke("auth:official-login", providerId),
  addRelay: (input) => ipcRenderer.invoke("provider:add-relay", input),
  addAccount: (input) => ipcRenderer.invoke("provider:add-account", input),
  removeProvider: (providerId) => ipcRenderer.invoke("provider:remove", providerId),
  saveProviderKey: (input) => ipcRenderer.invoke("provider:save-key", input),
  claudeModels: (input) => ipcRenderer.invoke("provider:claude-models", input),
  configureClaude: (input) => ipcRenderer.invoke("provider:configure-claude", input),
  providerBalance: (providerId) => ipcRenderer.invoke("provider:balance", providerId),
  setRecordHome: (directory) => ipcRenderer.invoke("settings:set-record-home", directory),
  addProject: (input) => ipcRenderer.invoke("project:add", input),
  renameProject: (input) => ipcRenderer.invoke("project:rename", input),
  deleteProject: (input) => ipcRenderer.invoke("project:delete", input),
  assignThreadToProject: (input) => ipcRenderer.invoke("project:assign-thread", input),
  saveThreadSettings: (input) => ipcRenderer.invoke("thread:save-settings", input),
  renameThreadLocal: (input) => ipcRenderer.invoke("thread:rename-local", input),
  archiveThreadLocal: (threadId) => ipcRenderer.invoke("thread:archive-local", threadId),
  unarchiveThreadLocal: (threadId) => ipcRenderer.invoke("thread:unarchive-local", threadId),
  hideThread: (input) => ipcRenderer.invoke("thread:hide", input),
  restoreThread: (threadId) => ipcRenderer.invoke("thread:restore", threadId),
  deleteThreadNow: (threadId) => ipcRenderer.invoke("thread:delete-now", threadId),
  saveScheduledTask: (input) => ipcRenderer.invoke("task:save", input),
  removeScheduledTask: (taskId) => ipcRenderer.invoke("task:remove", taskId),
  setScheduledTaskEnabled: (input) => ipcRenderer.invoke("task:set-enabled", input),
  openExternal: (target) => ipcRenderer.invoke("url:open", target),
  connect: (provider) => ipcRenderer.invoke("codex:connect", provider),
  listThreads: (query) => ipcRenderer.invoke("codex:list", query),
  listModels: () => ipcRenderer.invoke("codex:models"),
  listSkills: (payload) => ipcRenderer.invoke("codex:skills", payload),
  readThread: (threadId) => ipcRenderer.invoke("codex:read", threadId),
  readThreadWindow: (payload) => ipcRenderer.invoke("codex:read-window", payload),
  accountStatus: () => ipcRenderer.invoke("codex:account-status"),
  resumeThread: (payload) => ipcRenderer.invoke("codex:resume", payload),
  startThread: (payload) => ipcRenderer.invoke("codex:start-thread", payload),
  startTurn: (payload) => ipcRenderer.invoke("codex:start-turn", payload),
  renameThread: (payload) => ipcRenderer.invoke("codex:rename", payload),
  interruptTurn: (payload) => ipcRenderer.invoke("codex:interrupt", payload),
  answerApproval: (payload) => ipcRenderer.invoke("codex:approval-response", payload),
  onEvent: (handler) => ipcRenderer.on("codex:event", (_event, value) => handler(value)),
  onApproval: (handler) => ipcRenderer.on("codex:approval", (_event, value) => handler(value)),
  onDiagnostic: (handler) => ipcRenderer.on("codex:diagnostic", (_event, value) => handler(value)),
  onDisconnected: (handler) => ipcRenderer.on("codex:disconnected", (_event, value) => handler(value)),
  onStoreChanged: (handler) => ipcRenderer.on("app:store-changed", (_event, value) => handler(value)),
});
